apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-fsgroup-in-sparkapplication-binding
spec:
  policyName: deny-fsgroup-in-sparkapplication
  validationActions: ["Deny"]
  matchResources: {}